version: '3.9'

services:
  keycloak:
    env_file: ${DOT_ENV_FILE:-.env}
    # Ensure specific environment variables are ALWAYS available.
    environment:
      KC_CACHE: ispn
      KC_DB: ${KC_DB:-postgres}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD:-docker}
      KC_DB_URL: ${KC_DB_URL:-jdbc:postgresql://${KC_DB_URL_HOST:-host.docker.internal}:${KC_DB_PORT:-5432}/${KC_DB_NAME:-keycloak}}
      KC_DB_USERNAME: ${KC_DB_USERNAME:-postgres}
      # Enable health support
      KC_HEALTH_ENABLED: ${KC_HEALTH_ENABLED:-true}
      # Enable metrics support
      KC_METRICS_ENABLED: ${KC_METRICS_ENABLED:-true}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD:-2GettaGoodPass!!}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN:-SuperAdmin}
    container_name: ${KC_CONTAINER_NAME:-keycloak_acc}
    command:
      - ${KC_START_CMD:-start-dev}
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        keycloakVersion: ${KC_VERSION:-21.1.1}
    image: ${KC_IMAGE_NAME:-${KC_CONTAINER_NAME:-keycloak_acc}}:${KC_IMAGE_TAG:-latest}
    ports:
      - ${KC_HOST_PORT:-8180}:${KC_HTTP_PORT:-8080}
    volumes:
      - ./conf:/opt/keycloak/conf
    logging:
      options:
        max-size: '10m'
        max-file: '3'
